### PR TITLE
Fix Snap - Make an interaction that modifies MapBrowserEvent

### PR DESCRIPTION
**Pull request by adube**
coordinate and pixel inner properties.

@fperucic, I think that this way it'll work properly.  Can you confirm ?

### CODE REVIEW

**Comment by adube** [comment]
Or at least, it would work properly.  I reverted all changes made to modify and merged all of my commits into one.  If it looks okay to you, I'll apply then in the official snap branch.

**Comment by fperucic** [comment]
i guess it is ok. you can try to apply it. does it pass the build?

**Comment by adube** [comment]
I don't know yet.  We'll know once I merge.  I'll make the fixes, if required.  Thanks a bunch.

**Comment by fperucic** [comment]
but you can find out by executeing `./build.py ci` :)

**Comment by adube** [comment]
Oh, I talked too soon.  I got an e-mail from Travis, It does.

**Comment by adube** [comment]
Yes, you're right :)

**Comment by fperucic** [comment]
nice

**Pull request closed without merging**
